name = input("Enter your name: ")
print("Hello " + name) 
a = int(input("Enter first number you need: "))
b = int(input("Enter second number you need: "))
print("a + b = %d" % (a + b))
print("a x b = ", str(int(a) * float(b)))
